# Generated by Django 4.1.6 on 2023-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
