# Generated by Django 4.1.6 on 2023-02-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
