# Generated by Django 4.1.6 on 2023-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
